# spring.application.name=csu33012-2425-project19
# spoonacular.api.key=REDACTED

# spring.datasource.url=jdbc:mysql://localhost:3306/recipe_db
# spring.datasource.username=root
# spring.datasource.password=RandomPassword
# spring.jpa.hibernate.ddl-auto=update

spring.application.name=csu33012-2425-project19
spoonacular.api.key=REDACTED

spring.datasource.url=jdbc:mysql://localhost:3306/recipe_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=RandomPassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

